# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('pic', models.FileField(upload_to=b'')),
                ('phone', models.IntegerField()),
                ('home_add', models.TextField()),
                ('carno', models.CharField(max_length=100)),
                ('identity', models.FileField(upload_to=b'')),
                ('password', models.CharField(max_length=100)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
