# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-07 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='identity',
            field=models.FileField(max_length=10485760, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='user',
            name='pic',
            field=models.FileField(max_length=10485760, null=True, upload_to=b''),
        ),
    ]
