# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver_request',
            name='player_id',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
